services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    image: aorus22/video-player-web:latest
    container_name: video-player-web
    restart: unless-stopped
    ports:
      - "6431:5000"
